// Columns of public.announcements that authenticated clients are allowed to SELECT.
// The 3 job_contact_person_* columns are intentionally excluded — they are
// readable only via the SECURITY DEFINER RPC `get_announcement_contact(uuid)`.
// Using this list instead of `select("*")` avoids "permission denied for column"
// errors after the column-level grant tightening in migration 20260617090929.
export const ANNOUNCEMENT_SAFE_COLUMNS = [
  "id",
  "restaurant_id",
  "service_date",
  "service_time",
  "end_time",
  "end_date",
  "duration_hours",
  "shift_duration_hours",
  "is_long_shift",
  "long_shift_reason",
  "speed",
  "tariff_type",
  "tariff_amount",
  "location_address",
  "location_lat",
  "location_lng",
  "deposit_paid",
  "expires_at",
  "status",
  "assigned_worker_id",
  "created_at",
  "notes",
  "license_requirement",
  "language_requirements",
  "tattoos_allowed",
  "piercings_allowed",
  "beard_allowed",
  "required_skills",
  "dress_code_items",
  "dress_code_notes",
  "job_address",
  "job_city",
  "job_province",
  "job_postal_code",
  "job_country",
  "job_latitude",
  "job_longitude",
  "job_access_restrictions",
  "job_additional_directions",
  "job_location_notes",
  "cancelled_at",
  "cancellation_note",
  "cancellation_reason",
  "cancelled_by",
  "reopened_at",
  "reopened_after_worker_cancellation",
  "reused_from_announcement_id",
  "languages",
  "professional_profile",
  "seed_batch_id",
  "is_demo",
].join(", ");