export type AuditShot = {
  id: string;
  title: string;
  role: "Pubblico" | "Lavoratore" | "Ristoratore" | "Sistema" | "Popup/Stato";
  route: string;
  state: string;
  viewport: string;
  file: string;
  status: "generated" | "requires_credentials" | "requires_data" | "manual";
  notes: string[];
};

const note = (...items: string[]) => items;

export const auditShots: AuditShot[] = [
  { id: "01", title: "Homepage", role: "Pubblico", route: "/", state: "pubblica", viewport: "desktop 1280×1800", file: "01-home-desktop.png", status: "generated", notes: note("Value proposition", "gerarchia CTA", "fiducia percepita", "leggibilità above the fold") },
  { id: "02", title: "Homepage", role: "Pubblico", route: "/", state: "pubblica", viewport: "mobile 412×900", file: "02-home-mobile.png", status: "generated", notes: note("Priorità mobile", "CTA primaria", "leggibilità testi", "spaziatura") },
  { id: "03", title: "Come funziona", role: "Pubblico", route: "/come-funziona", state: "pubblica", viewport: "desktop 1280×1800", file: "03-come-funziona-desktop.png", status: "generated", notes: note("Chiarezza passaggi", "distinzione lavoratore/ristoratore", "CTA finale") },
  { id: "04", title: "Come funziona", role: "Pubblico", route: "/come-funziona", state: "pubblica", viewport: "mobile 412×900", file: "04-come-funziona-mobile.png", status: "generated", notes: note("Sequenza mobile", "densità testo", "comprensione del flusso") },
  { id: "05", title: "Login", role: "Pubblico", route: "/auth", state: "login", viewport: "desktop 1280×1800", file: "05-login-desktop.png", status: "generated", notes: note("Chiarezza accesso", "social login", "recupero password", "contrasto bottoni") },
  { id: "06", title: "Login", role: "Pubblico", route: "/auth", state: "login", viewport: "mobile 412×900", file: "06-login-mobile.png", status: "generated", notes: note("Usabilità form mobile", "dimensione campi", "CTA") },
  { id: "07", title: "Registrazione lavoratore", role: "Pubblico", route: "/auth?role=worker", state: "registrazione", viewport: "mobile 412×900", file: "07-register-worker-mobile.png", status: "generated", notes: note("Friction form", "validazioni", "selezione ruolo", "chiarezza requisiti password") },
  { id: "08", title: "Registrazione ristoratore", role: "Pubblico", route: "/auth?role=restaurant", state: "registrazione", viewport: "mobile 412×900", file: "08-register-restaurant-mobile.png", status: "generated", notes: note("Friction form", "campo età referente", "fiducia e chiarezza") },
  { id: "09", title: "Recupero password", role: "Pubblico", route: "/reset-password", state: "default", viewport: "mobile 412×900", file: "09-reset-password-mobile.png", status: "generated", notes: note("Chiarezza istruzioni", "visibilità CTA", "tono del messaggio") },
  { id: "10", title: "Errore login", role: "Sistema", route: "/auth", state: "credenziali errate", viewport: "mobile 412×900", file: "10-login-error-mobile.png", status: "generated", notes: note("Messaggio errore", "recuperabilità", "tono", "visibilità feedback") },
  { id: "11", title: "Errore registrazione", role: "Sistema", route: "/auth?role=worker", state: "form non valido", viewport: "mobile 412×900", file: "11-register-error-mobile.png", status: "generated", notes: note("Validazioni inline", "chiarezza campi obbligatori", "frizione percepita") },

  { id: "12", title: "Dashboard lavoratore", role: "Lavoratore", route: "/dashboard", state: "autenticato come lavoratore", viewport: "mobile 412×900", file: "12-worker-dashboard-mobile.png", status: "requires_credentials", notes: note("Priorità operative", "card principali", "navigazione", "chiarezza stato profilo") },
  { id: "13", title: "Profilo lavoratore", role: "Lavoratore", route: "/profile", state: "autenticato come lavoratore", viewport: "mobile 412×900", file: "13-worker-profile-mobile.png", status: "requires_credentials", notes: note("Completezza informazioni", "modifica profilo", "privacy", "reputazione") },
  { id: "14", title: "Modifica profilo lavoratore", role: "Lavoratore", route: "/profile", state: "sezione modifica", viewport: "desktop 1280×1800", file: "14-worker-profile-edit-desktop.png", status: "requires_credentials", notes: note("Layout form", "campi critici", "leggibilità desktop") },
  { id: "15", title: "Disponibilità", role: "Lavoratore", route: "/availability", state: "autenticato come lavoratore", viewport: "mobile 412×900", file: "15-worker-availability-mobile.png", status: "requires_credentials", notes: note("Controlli disponibilità", "giorni/fasce", "CTA salvataggio", "stati vuoti") },
  { id: "16", title: "Ricerca offerte / Jobs", role: "Lavoratore", route: "/jobs", state: "autenticato come lavoratore", viewport: "mobile 412×900", file: "16-worker-jobs-mobile.png", status: "requires_credentials", notes: note("Lista offerte", "filtri", "CTA candidatura", "gerarchia card") },
  { id: "17", title: "Dettaglio offerta", role: "Lavoratore", route: "/jobs", state: "offerta aperta", viewport: "mobile 412×900", file: "17-worker-job-detail-mobile.png", status: "requires_data", notes: note("Dati turno", "privacy contatti", "tariffa", "azione candidatura") },
  { id: "18", title: "Candidatura inviata", role: "Lavoratore", route: "/jobs", state: "success dopo candidatura", viewport: "mobile 412×900", file: "18-worker-application-sent-mobile.png", status: "manual", notes: note("Feedback successo", "prossimo passo", "rassicurazione") },
  { id: "19", title: "Offerte ricevute", role: "Lavoratore", route: "/jobs", state: "nuove/da rispondere", viewport: "mobile 412×900", file: "19-worker-offers-received-mobile.png", status: "requires_credentials", notes: note("Scansione stati", "badge", "urgenza", "CTA") },
  { id: "20", title: "Offerte accettate", role: "Lavoratore", route: "/jobs", state: "accettate", viewport: "mobile 412×900", file: "20-worker-offers-accepted-mobile.png", status: "requires_credentials", notes: note("Stato conferma", "contatti sbloccati", "chat") },
  { id: "21", title: "Offerte rifiutate", role: "Lavoratore", route: "/jobs", state: "rifiutate", viewport: "mobile 412×900", file: "21-worker-offers-rejected-mobile.png", status: "requires_credentials", notes: note("Archiviazione", "chiarezza motivi", "recuperabilità") },
  { id: "22", title: "Turni confermati", role: "Lavoratore", route: "/shifts?tab=assigned", state: "confermati", viewport: "mobile 412×900", file: "22-worker-shifts-confirmed-mobile.png", status: "requires_credentials", notes: note("Informazioni turno", "azioni disponibili", "orario e luogo") },
  { id: "23", title: "Turni completati", role: "Lavoratore", route: "/shifts?tab=completed", state: "completati", viewport: "mobile 412×900", file: "23-worker-shifts-completed-mobile.png", status: "requires_credentials", notes: note("Storico", "recensioni", "compenso") },
  { id: "24", title: "Turni annullati", role: "Lavoratore", route: "/shifts?tab=past", state: "annullati", viewport: "mobile 412×900", file: "24-worker-shifts-cancelled-mobile.png", status: "requires_credentials", notes: note("Comprensione annullamento", "tono", "azioni residue") },
  { id: "25", title: "Recensioni lavoratore", role: "Lavoratore", route: "/profile", state: "recensioni", viewport: "mobile 412×900", file: "25-worker-reviews-mobile.png", status: "requires_credentials", notes: note("Fiducia", "reputazione", "badge") },
  { id: "26", title: "Recensione da lasciare", role: "Lavoratore", route: "/reviews/:id", state: "popup recensione", viewport: "mobile 412×900", file: "26-worker-review-to-leave-mobile.png", status: "requires_data", notes: note("Friction rating", "etichette", "commento", "CTA invio") },
  { id: "27", title: "Messaggi/chat lavoratore", role: "Lavoratore", route: "/messages", state: "autenticato", viewport: "mobile 412×900", file: "27-worker-messages-mobile.png", status: "requires_credentials", notes: note("Lista chat", "thread", "privacy", "leggibilità bolle") },
  { id: "28", title: "Notifiche lavoratore", role: "Lavoratore", route: "/notifications", state: "autenticato", viewport: "mobile 412×900", file: "28-worker-notifications-mobile.png", status: "requires_credentials", notes: note("Priorità notifiche", "stato letto", "CTA contestuali") },
  { id: "29", title: "Impostazioni account lavoratore", role: "Lavoratore", route: "/profile", state: "account", viewport: "mobile 412×900", file: "29-worker-account-settings-mobile.png", status: "requires_credentials", notes: note("Cambio password", "documenti", "eliminazione account") },
  { id: "30", title: "Cambio password", role: "Lavoratore", route: "/profile", state: "form cambio password", viewport: "mobile 412×900", file: "30-worker-change-password-mobile.png", status: "requires_credentials", notes: note("Chiarezza campi", "sicurezza percepita", "feedback errori") },
  { id: "31", title: "Guida/onboarding lavoratore", role: "Lavoratore", route: "/onboarding", state: "autenticato", viewport: "mobile 412×900", file: "31-worker-onboarding-mobile.png", status: "requires_credentials", notes: note("Progressione", "campi obbligatori", "supporto iniziale") },
  { id: "32", title: "Help/supporto lavoratore", role: "Lavoratore", route: "/messages", state: "supporto/assistente se presente", viewport: "mobile 412×900", file: "32-worker-help-support-mobile.png", status: "requires_credentials", notes: note("Visibilità assistenza", "chiarezza percorso supporto") },

  { id: "33", title: "Dashboard ristoratore", role: "Ristoratore", route: "/dashboard", state: "autenticato come ristoratore", viewport: "desktop 1280×1800", file: "33-restaurant-dashboard-desktop.png", status: "requires_credentials", notes: note("Priorità operative", "annunci/candidature", "crediti", "navigazione") },
  { id: "34", title: "Profilo locale", role: "Ristoratore", route: "/profile", state: "autenticato come ristoratore", viewport: "mobile 412×900", file: "34-restaurant-profile-mobile.png", status: "requires_credentials", notes: note("Fiducia", "dati locale", "contatti", "completezza") },
  { id: "35", title: "Modifica profilo locale", role: "Ristoratore", route: "/profile", state: "modifica", viewport: "desktop 1280×1800", file: "35-restaurant-profile-edit-desktop.png", status: "requires_credentials", notes: note("Form locale", "campi contatto", "leggibilità") },
  { id: "36", title: "Pubblicazione annuncio", role: "Ristoratore", route: "/announcements/new", state: "nuovo annuncio", viewport: "mobile 412×900", file: "36-restaurant-announcement-new-mobile.png", status: "requires_credentials", notes: note("Friction creazione", "tariffa", "data/ora", "CTA pubblica") },
  { id: "37", title: "Elenco annunci", role: "Ristoratore", route: "/announcements", state: "lista", viewport: "mobile 412×900", file: "37-restaurant-announcements-mobile.png", status: "requires_credentials", notes: note("Card annuncio", "stati", "candidature", "CTA nuovo") },
  { id: "38", title: "Dettaglio annuncio", role: "Ristoratore", route: "/announcements/:id", state: "dettaglio", viewport: "mobile 412×900", file: "38-restaurant-announcement-detail-mobile.png", status: "requires_data", notes: note("Riepilogo turno", "azioni", "privacy", "mappa") },
  { id: "39", title: "Candidature ricevute", role: "Ristoratore", route: "/announcements/:id?section=candidature", state: "candidature", viewport: "mobile 412×900", file: "39-restaurant-applications-mobile.png", status: "requires_data", notes: note("Lista candidati", "CTA accetta/rifiuta", "privacy bloccata") },
  { id: "40", title: "Dettaglio candidatura", role: "Ristoratore", route: "/announcements/:id?section=candidature", state: "candidato aperto", viewport: "mobile 412×900", file: "40-restaurant-application-detail-mobile.png", status: "requires_data", notes: note("Profilo candidato", "esperienza", "contatti", "proposta") },
  { id: "41", title: "Ricerca lavoratori", role: "Ristoratore", route: "/workers", state: "autenticato", viewport: "mobile 412×900", file: "41-restaurant-workers-mobile.png", status: "requires_credentials", notes: note("Filtri", "card lavoratore", "privacy sanitizzata", "CTA invito") },
  { id: "42", title: "Dettaglio lavoratore", role: "Ristoratore", route: "/workers_/:id", state: "dettaglio", viewport: "mobile 412×900", file: "42-restaurant-worker-detail-mobile.png", status: "requires_data", notes: note("Fiducia", "contatti bloccati/sbloccati", "recensioni", "CTA") },
  { id: "43", title: "Invito diretto", role: "Ristoratore", route: "/workers", state: "dialog invito", viewport: "mobile 412×900", file: "43-restaurant-direct-invite-mobile.png", status: "manual", notes: note("Comprensione proposta", "campi obbligatori", "frizione") },
  { id: "44", title: "Proposta tariffa", role: "Ristoratore", route: "/workers", state: "controproposta", viewport: "mobile 412×900", file: "44-restaurant-rate-proposal-mobile.png", status: "manual", notes: note("Chiarezza importi", "conferma", "rischio errore") },
  { id: "45", title: "Turni confermati ristoratore", role: "Ristoratore", route: "/shifts?tab=assigned", state: "confermati", viewport: "mobile 412×900", file: "45-restaurant-shifts-confirmed-mobile.png", status: "requires_credentials", notes: note("Gestione turno", "contatti", "azioni no-show/annulla") },
  { id: "46", title: "Turni completati ristoratore", role: "Ristoratore", route: "/shifts?tab=completed", state: "completati", viewport: "mobile 412×900", file: "46-restaurant-shifts-completed-mobile.png", status: "requires_credentials", notes: note("Storico", "recensioni", "pagamento") },
  { id: "47", title: "Turni annullati ristoratore", role: "Ristoratore", route: "/shifts?tab=past", state: "annullati", viewport: "mobile 412×900", file: "47-restaurant-shifts-cancelled-mobile.png", status: "requires_credentials", notes: note("Motivo annullamento", "recuperabilità", "tono") },
  { id: "48", title: "Crediti/pagamenti", role: "Ristoratore", route: "/billing", state: "pagamenti", viewport: "mobile 412×900", file: "48-restaurant-billing-mobile.png", status: "requires_credentials", notes: note("Chiarezza piani", "fiducia pagamento", "CTA acquisto", "storico") },
  { id: "49", title: "Recensioni ristoratore", role: "Ristoratore", route: "/ristoratore/recensioni", state: "recensioni", viewport: "mobile 412×900", file: "49-restaurant-reviews-mobile.png", status: "requires_credentials", notes: note("Reputazione locale", "badge", "fiducia") },
  { id: "50", title: "Messaggi/chat ristoratore", role: "Ristoratore", route: "/messages", state: "autenticato", viewport: "mobile 412×900", file: "50-restaurant-messages-mobile.png", status: "requires_credentials", notes: note("Lista candidature", "thread", "stato conferme", "leggibilità") },
  { id: "51", title: "Notifiche ristoratore", role: "Ristoratore", route: "/notifications", state: "autenticato", viewport: "mobile 412×900", file: "51-restaurant-notifications-mobile.png", status: "requires_credentials", notes: note("Priorità notifiche", "nuove candidature", "azioni rapide") },
  { id: "52", title: "Impostazioni account ristoratore", role: "Ristoratore", route: "/profile", state: "account", viewport: "mobile 412×900", file: "52-restaurant-account-settings-mobile.png", status: "requires_credentials", notes: note("Password", "piano", "documenti", "eliminazione account") },
  { id: "53", title: "Guida/onboarding ristoratore", role: "Ristoratore", route: "/onboarding", state: "autenticato", viewport: "mobile 412×900", file: "53-restaurant-onboarding-mobile.png", status: "requires_credentials", notes: note("Completezza profilo locale", "passi guidati", "CTA") },
  { id: "54", title: "Help/supporto ristoratore", role: "Ristoratore", route: "/messages", state: "supporto/assistente se presente", viewport: "mobile 412×900", file: "54-restaurant-help-support-mobile.png", status: "requires_credentials", notes: note("Visibilità supporto", "comprensione aiuto") },

  { id: "55", title: "Popup guida iniziale", role: "Popup/Stato", route: "/dashboard", state: "guided tour", viewport: "mobile 412×900", file: "55-popup-guided-tour-mobile.png", status: "manual", notes: note("Chiarezza guida", "dismiss", "non invasività") },
  { id: "56", title: "Popup conferma turno", role: "Popup/Stato", route: "/jobs", state: "conferma turno", viewport: "mobile 412×900", file: "56-popup-confirm-shift-mobile.png", status: "manual", notes: note("Rischio errore", "chiarezza riepilogo", "CTA") },
  { id: "57", title: "Popup annullamento turno", role: "Popup/Stato", route: "/shifts", state: "annullamento", viewport: "mobile 412×900", file: "57-popup-cancel-shift-mobile.png", status: "manual", notes: note("Tono", "motivi", "conseguenze", "undo") },
  { id: "58", title: "Popup candidatura inviata", role: "Popup/Stato", route: "/jobs", state: "success candidatura", viewport: "mobile 412×900", file: "58-popup-application-sent-mobile.png", status: "manual", notes: note("Feedback", "prossimo passo", "fiducia") },
  { id: "59", title: "Popup offerta ricevuta", role: "Popup/Stato", route: "/jobs", state: "offerta ricevuta", viewport: "mobile 412×900", file: "59-popup-offer-received-mobile.png", status: "manual", notes: note("Urgenza", "chiarezza opzioni", "tariffa") },
  { id: "60", title: "Popup errore", role: "Popup/Stato", route: "/auth", state: "errore", viewport: "mobile 412×900", file: "60-popup-error-mobile.png", status: "manual", notes: note("Visibilità errore", "recuperabilità", "tono") },
  { id: "61", title: "Popup successo", role: "Popup/Stato", route: "/profile", state: "success", viewport: "mobile 412×900", file: "61-popup-success-mobile.png", status: "manual", notes: note("Feedback", "chiarezza prossimo passo") },
  { id: "62", title: "Popup recensione", role: "Popup/Stato", route: "/shifts", state: "recensione", viewport: "mobile 412×900", file: "62-popup-review-mobile.png", status: "requires_data", notes: note("Rating", "etichette", "commento", "CTA") },
  { id: "63", title: "Stato privacy bloccata", role: "Popup/Stato", route: "/workers", state: "contatti bloccati", viewport: "mobile 412×900", file: "63-privacy-locked-mobile.png", status: "requires_credentials", notes: note("Chiarezza privacy", "fiducia", "spiegazione sblocco") },
  { id: "64", title: "Stato privacy sbloccata", role: "Popup/Stato", route: "/jobs", state: "contatti sbloccati", viewport: "mobile 412×900", file: "64-privacy-unlocked-mobile.png", status: "requires_data", notes: note("Contatti dopo match", "gerarchia dati", "sicurezza percepita") },
  { id: "65", title: "Stato vuoto", role: "Popup/Stato", route: "/notifications", state: "nessun dato", viewport: "mobile 412×900", file: "65-empty-state-mobile.png", status: "requires_credentials", notes: note("Empty state", "azione successiva", "tono") },
  { id: "66", title: "Stato con dati", role: "Popup/Stato", route: "/dashboard", state: "dati presenti", viewport: "mobile 412×900", file: "66-data-state-mobile.png", status: "requires_credentials", notes: note("Gerarchia dati", "densità", "scansione") },
  { id: "67", title: "Loading", role: "Popup/Stato", route: "/dashboard", state: "loading", viewport: "mobile 412×900", file: "67-loading-state-mobile.png", status: "manual", notes: note("Feedback attesa", "layout shift", "chiarezza") },
  { id: "68", title: "Errore", role: "Popup/Stato", route: "/account-error", state: "errore sistema", viewport: "mobile 412×900", file: "68-error-state-mobile.png", status: "generated", notes: note("Messaggio errore", "azioni disponibili", "tono") },
  { id: "69", title: "Nessuna candidatura", role: "Popup/Stato", route: "/announcements/:id", state: "nessuna candidatura", viewport: "mobile 412×900", file: "69-no-applications-mobile.png", status: "requires_data", notes: note("Empty state ristoratore", "prossimo passo") },
  { id: "70", title: "Nessun turno", role: "Popup/Stato", route: "/shifts", state: "nessun turno", viewport: "mobile 412×900", file: "70-no-shifts-mobile.png", status: "requires_credentials", notes: note("Empty state turni", "CTA", "tono") },
  { id: "71", title: "Nessuna notifica", role: "Popup/Stato", route: "/notifications", state: "nessuna notifica", viewport: "mobile 412×900", file: "71-no-notifications-mobile.png", status: "requires_credentials", notes: note("Empty state notifiche", "chiarezza", "spaziatura") },
];

export function auditStatusLabel(status: AuditShot["status"]) {
  if (status === "generated") return "generato";
  if (status === "requires_credentials") return "da generare con credenziali audit";
  if (status === "requires_data") return "richiede dati/id reali";
  return "manuale/interazione richiesta";
}