import { createClient } from '@supabase/supabase-js';
const URL=process.env.SUPABASE_URL, ANON=process.env.SUPABASE_PUBLISHABLE_KEY;
const admin=createClient(URL,process.env.SB_SERVICE,{auth:{persistSession:false}});
const email=`f5b.${Date.now()}@pupillo.test`, pass='Test!12345aA';
const {data,error}=await admin.auth.admin.createUser({email,password:pass,email_confirm:true});
if(error) throw error;
const id=data.user.id;
await admin.from('user_roles').insert({user_id:id,role:'restaurant'});
const c=createClient(URL,ANON,{auth:{persistSession:false}});
await c.auth.signInWithPassword({email,password:pass});
console.log('own_select', await c.from('profiles').select('id,email').eq('id',id).then(x=>[x.data?.length,x.error]));
console.log('own_update_bio', JSON.stringify(await c.from('profiles').update({short_bio:'ok'}).eq('id',id).then(x=>x.error)));
console.log('own_update_city', JSON.stringify(await c.from('profiles').update({city:'Bologna'}).eq('id',id).then(x=>x.error)));
console.log('own_update_credits', JSON.stringify(await c.from('profiles').update({credits:999}).eq('id',id).then(x=>x.error)));
await admin.from('user_roles').delete().eq('user_id',id); await admin.auth.admin.deleteUser(id);
