import { createClient } from '@supabase/supabase-js';
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
const RID = process.argv[2];
const p = (k,v)=>console.log(k+':', JSON.stringify(v));
const { data: prof } = await sb.from('profiles').select('id,is_deleted,deleted_at,business_name,full_name,phone,email,contact_person_first_name,account_status').eq('id',RID).single();
p('profile', prof);
const { data: anns } = await sb.from('announcements').select('id,notes,status,cancellation_reason,location_address,job_address,job_contact_person_name,job_contact_person_phone,assigned_worker_id').eq('restaurant_id',RID).order('notes');
p('announcements', anns);
const { data: apps } = await sb.from('applications').select('id,announcement_id,worker_id,status').eq('restaurant_id',RID);
p('applications', apps);
const { data: sh } = await sb.from('shifts').select('id,worker_id,shift_date,status').eq('restaurant_id',RID);
p('shifts', sh);
const { data: rev } = await sb.from('reviews').select('id,direction,rating,author_id,target_id').or(`author_id.eq.${RID},target_id.eq.${RID}`);
p('reviews', rev);
const workers = [...new Set((apps||[]).map(a=>a.worker_id))];
const { data: notif } = await sb.from('notifications').select('user_id,title,link,dedupe_key,metadata').in('user_id', workers).order('created_at');
p('notifications', notif);
const { data: audit } = await sb.from('admin_audit_log').select('action,metadata,created_at').eq('target_user',RID).order('created_at');
p('audit', audit);
