/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as VerifyPhoneRouteImport } from './routes/verify-phone'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as RistoratoriRouteImport } from './routes/ristoratori'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistrationSuccessRouteImport } from './routes/registration-success'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MappaRouteImport } from './routes/mappa'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComeFunzionaRouteImport } from './routes/come-funziona'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIdRouteImport } from './routes/workers_.$id'
import { Route as RistoratoreCollaboratoriRouteImport } from './routes/ristoratore.collaboratori'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as AnnouncementsNewRouteImport } from './routes/announcements.new'
import { Route as AnnouncementsIdRouteImport } from './routes/announcements.$id'
import { Route as AdminResetTestDbRouteImport } from './routes/admin.reset-test-db'
import { Route as AdminBackendRouteImport } from './routes/admin.backend'
import { Route as RistoratoreTurniShiftIdRouteImport } from './routes/ristoratore.turni.$shiftId'
import { Route as RistoratoreAnnunciNuovoRouteImport } from './routes/ristoratore.annunci.nuovo'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksExpireStaleRouteImport } from './routes/api/public/hooks/expire-stale'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPhoneRoute = VerifyPhoneRouteImport.update({
  id: '/verify-phone',
  path: '/verify-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const RistoratoriRoute = RistoratoriRouteImport.update({
  id: '/ristoratori',
  path: '/ristoratori',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationSuccessRoute = RegistrationSuccessRouteImport.update({
  id: '/registration-success',
  path: '/registration-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MappaRoute = MappaRouteImport.update({
  id: '/mappa',
  path: '/mappa',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComeFunzionaRoute = ComeFunzionaRouteImport.update({
  id: '/come-funziona',
  path: '/come-funziona',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIdRoute = WorkersIdRouteImport.update({
  id: '/workers_/$id',
  path: '/workers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RistoratoreCollaboratoriRoute =
  RistoratoreCollaboratoriRouteImport.update({
    id: '/ristoratore/collaboratori',
    path: '/ristoratore/collaboratori',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/restaurants/$id',
  path: '/restaurants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const AnnouncementsNewRoute = AnnouncementsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const AnnouncementsIdRoute = AnnouncementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const AdminResetTestDbRoute = AdminResetTestDbRouteImport.update({
  id: '/reset-test-db',
  path: '/reset-test-db',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackendRoute = AdminBackendRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => AdminRoute,
} as any)
const RistoratoreTurniShiftIdRoute = RistoratoreTurniShiftIdRouteImport.update({
  id: '/ristoratore/turni/$shiftId',
  path: '/ristoratore/turni/$shiftId',
  getParentRoute: () => rootRouteImport,
} as any)
const RistoratoreAnnunciNuovoRoute = RistoratoreAnnunciNuovoRouteImport.update({
  id: '/ristoratore/annunci/nuovo',
  path: '/ristoratore/annunci/nuovo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExpireStaleRoute =
  ApiPublicHooksExpireStaleRouteImport.update({
    id: '/api/public/hooks/expire-stale',
    path: '/api/public/hooks/expire-stale',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/browse': typeof BrowseRoute
  '/come-funziona': typeof ComeFunzionaRoute
  '/dashboard': typeof DashboardRoute
  '/forbidden': typeof ForbiddenRoute
  '/jobs': typeof JobsRoute
  '/mappa': typeof MappaRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ristoratori': typeof RistoratoriRoute
  '/shifts': typeof ShiftsRoute
  '/terms': typeof TermsRoute
  '/verify-phone': typeof VerifyPhoneRoute
  '/workers': typeof WorkersRoute
  '/admin/backend': typeof AdminBackendRoute
  '/admin/reset-test-db': typeof AdminResetTestDbRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/announcements/new': typeof AnnouncementsNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/ristoratore/collaboratori': typeof RistoratoreCollaboratoriRoute
  '/workers/$id': typeof WorkersIdRoute
  '/ristoratore/annunci/nuovo': typeof RistoratoreAnnunciNuovoRoute
  '/ristoratore/turni/$shiftId': typeof RistoratoreTurniShiftIdRoute
  '/api/public/hooks/expire-stale': typeof ApiPublicHooksExpireStaleRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/browse': typeof BrowseRoute
  '/come-funziona': typeof ComeFunzionaRoute
  '/dashboard': typeof DashboardRoute
  '/forbidden': typeof ForbiddenRoute
  '/jobs': typeof JobsRoute
  '/mappa': typeof MappaRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ristoratori': typeof RistoratoriRoute
  '/shifts': typeof ShiftsRoute
  '/terms': typeof TermsRoute
  '/verify-phone': typeof VerifyPhoneRoute
  '/workers': typeof WorkersRoute
  '/admin/backend': typeof AdminBackendRoute
  '/admin/reset-test-db': typeof AdminResetTestDbRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/announcements/new': typeof AnnouncementsNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/ristoratore/collaboratori': typeof RistoratoreCollaboratoriRoute
  '/workers/$id': typeof WorkersIdRoute
  '/ristoratore/annunci/nuovo': typeof RistoratoreAnnunciNuovoRoute
  '/ristoratore/turni/$shiftId': typeof RistoratoreTurniShiftIdRoute
  '/api/public/hooks/expire-stale': typeof ApiPublicHooksExpireStaleRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/browse': typeof BrowseRoute
  '/come-funziona': typeof ComeFunzionaRoute
  '/dashboard': typeof DashboardRoute
  '/forbidden': typeof ForbiddenRoute
  '/jobs': typeof JobsRoute
  '/mappa': typeof MappaRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ristoratori': typeof RistoratoriRoute
  '/shifts': typeof ShiftsRoute
  '/terms': typeof TermsRoute
  '/verify-phone': typeof VerifyPhoneRoute
  '/workers': typeof WorkersRoute
  '/admin/backend': typeof AdminBackendRoute
  '/admin/reset-test-db': typeof AdminResetTestDbRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/announcements/new': typeof AnnouncementsNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/ristoratore/collaboratori': typeof RistoratoreCollaboratoriRoute
  '/workers_/$id': typeof WorkersIdRoute
  '/ristoratore/annunci/nuovo': typeof RistoratoreAnnunciNuovoRoute
  '/ristoratore/turni/$shiftId': typeof RistoratoreTurniShiftIdRoute
  '/api/public/hooks/expire-stale': typeof ApiPublicHooksExpireStaleRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/auth'
    | '/billing'
    | '/browse'
    | '/come-funziona'
    | '/dashboard'
    | '/forbidden'
    | '/jobs'
    | '/mappa'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/registration-success'
    | '/reset-password'
    | '/ristoratori'
    | '/shifts'
    | '/terms'
    | '/verify-phone'
    | '/workers'
    | '/admin/backend'
    | '/admin/reset-test-db'
    | '/announcements/$id'
    | '/announcements/new'
    | '/messages/$id'
    | '/restaurants/$id'
    | '/ristoratore/collaboratori'
    | '/workers/$id'
    | '/ristoratore/annunci/nuovo'
    | '/ristoratore/turni/$shiftId'
    | '/api/public/hooks/expire-stale'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/announcements'
    | '/auth'
    | '/billing'
    | '/browse'
    | '/come-funziona'
    | '/dashboard'
    | '/forbidden'
    | '/jobs'
    | '/mappa'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/registration-success'
    | '/reset-password'
    | '/ristoratori'
    | '/shifts'
    | '/terms'
    | '/verify-phone'
    | '/workers'
    | '/admin/backend'
    | '/admin/reset-test-db'
    | '/announcements/$id'
    | '/announcements/new'
    | '/messages/$id'
    | '/restaurants/$id'
    | '/ristoratore/collaboratori'
    | '/workers/$id'
    | '/ristoratore/annunci/nuovo'
    | '/ristoratore/turni/$shiftId'
    | '/api/public/hooks/expire-stale'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/auth'
    | '/billing'
    | '/browse'
    | '/come-funziona'
    | '/dashboard'
    | '/forbidden'
    | '/jobs'
    | '/mappa'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/registration-success'
    | '/reset-password'
    | '/ristoratori'
    | '/shifts'
    | '/terms'
    | '/verify-phone'
    | '/workers'
    | '/admin/backend'
    | '/admin/reset-test-db'
    | '/announcements/$id'
    | '/announcements/new'
    | '/messages/$id'
    | '/restaurants/$id'
    | '/ristoratore/collaboratori'
    | '/workers_/$id'
    | '/ristoratore/annunci/nuovo'
    | '/ristoratore/turni/$shiftId'
    | '/api/public/hooks/expire-stale'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  BrowseRoute: typeof BrowseRoute
  ComeFunzionaRoute: typeof ComeFunzionaRoute
  DashboardRoute: typeof DashboardRoute
  ForbiddenRoute: typeof ForbiddenRoute
  JobsRoute: typeof JobsRoute
  MappaRoute: typeof MappaRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RegistrationSuccessRoute: typeof RegistrationSuccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RistoratoriRoute: typeof RistoratoriRoute
  ShiftsRoute: typeof ShiftsRoute
  TermsRoute: typeof TermsRoute
  VerifyPhoneRoute: typeof VerifyPhoneRoute
  WorkersRoute: typeof WorkersRoute
  RestaurantsIdRoute: typeof RestaurantsIdRoute
  RistoratoreCollaboratoriRoute: typeof RistoratoreCollaboratoriRoute
  WorkersIdRoute: typeof WorkersIdRoute
  RistoratoreAnnunciNuovoRoute: typeof RistoratoreAnnunciNuovoRoute
  RistoratoreTurniShiftIdRoute: typeof RistoratoreTurniShiftIdRoute
  ApiPublicHooksExpireStaleRoute: typeof ApiPublicHooksExpireStaleRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-phone': {
      id: '/verify-phone'
      path: '/verify-phone'
      fullPath: '/verify-phone'
      preLoaderRoute: typeof VerifyPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ristoratori': {
      id: '/ristoratori'
      path: '/ristoratori'
      fullPath: '/ristoratori'
      preLoaderRoute: typeof RistoratoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-success': {
      id: '/registration-success'
      path: '/registration-success'
      fullPath: '/registration-success'
      preLoaderRoute: typeof RegistrationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mappa': {
      id: '/mappa'
      path: '/mappa'
      fullPath: '/mappa'
      preLoaderRoute: typeof MappaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/come-funziona': {
      id: '/come-funziona'
      path: '/come-funziona'
      fullPath: '/come-funziona'
      preLoaderRoute: typeof ComeFunzionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers_/$id': {
      id: '/workers_/$id'
      path: '/workers/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof WorkersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ristoratore/collaboratori': {
      id: '/ristoratore/collaboratori'
      path: '/ristoratore/collaboratori'
      fullPath: '/ristoratore/collaboratori'
      preLoaderRoute: typeof RistoratoreCollaboratoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/announcements/new': {
      id: '/announcements/new'
      path: '/new'
      fullPath: '/announcements/new'
      preLoaderRoute: typeof AnnouncementsNewRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/announcements/$id': {
      id: '/announcements/$id'
      path: '/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AnnouncementsIdRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/admin/reset-test-db': {
      id: '/admin/reset-test-db'
      path: '/reset-test-db'
      fullPath: '/admin/reset-test-db'
      preLoaderRoute: typeof AdminResetTestDbRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backend': {
      id: '/admin/backend'
      path: '/backend'
      fullPath: '/admin/backend'
      preLoaderRoute: typeof AdminBackendRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ristoratore/turni/$shiftId': {
      id: '/ristoratore/turni/$shiftId'
      path: '/ristoratore/turni/$shiftId'
      fullPath: '/ristoratore/turni/$shiftId'
      preLoaderRoute: typeof RistoratoreTurniShiftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ristoratore/annunci/nuovo': {
      id: '/ristoratore/annunci/nuovo'
      path: '/ristoratore/annunci/nuovo'
      fullPath: '/ristoratore/annunci/nuovo'
      preLoaderRoute: typeof RistoratoreAnnunciNuovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expire-stale': {
      id: '/api/public/hooks/expire-stale'
      path: '/api/public/hooks/expire-stale'
      fullPath: '/api/public/hooks/expire-stale'
      preLoaderRoute: typeof ApiPublicHooksExpireStaleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBackendRoute: typeof AdminBackendRoute
  AdminResetTestDbRoute: typeof AdminResetTestDbRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBackendRoute: AdminBackendRoute,
  AdminResetTestDbRoute: AdminResetTestDbRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AnnouncementsRouteChildren {
  AnnouncementsIdRoute: typeof AnnouncementsIdRoute
  AnnouncementsNewRoute: typeof AnnouncementsNewRoute
}

const AnnouncementsRouteChildren: AnnouncementsRouteChildren = {
  AnnouncementsIdRoute: AnnouncementsIdRoute,
  AnnouncementsNewRoute: AnnouncementsNewRoute,
}

const AnnouncementsRouteWithChildren = AnnouncementsRoute._addFileChildren(
  AnnouncementsRouteChildren,
)

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRouteWithChildren,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  BrowseRoute: BrowseRoute,
  ComeFunzionaRoute: ComeFunzionaRoute,
  DashboardRoute: DashboardRoute,
  ForbiddenRoute: ForbiddenRoute,
  JobsRoute: JobsRoute,
  MappaRoute: MappaRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RegistrationSuccessRoute: RegistrationSuccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RistoratoriRoute: RistoratoriRoute,
  ShiftsRoute: ShiftsRoute,
  TermsRoute: TermsRoute,
  VerifyPhoneRoute: VerifyPhoneRoute,
  WorkersRoute: WorkersRoute,
  RestaurantsIdRoute: RestaurantsIdRoute,
  RistoratoreCollaboratoriRoute: RistoratoreCollaboratoriRoute,
  WorkersIdRoute: WorkersIdRoute,
  RistoratoreAnnunciNuovoRoute: RistoratoreAnnunciNuovoRoute,
  RistoratoreTurniShiftIdRoute: RistoratoreTurniShiftIdRoute,
  ApiPublicHooksExpireStaleRoute: ApiPublicHooksExpireStaleRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
